"""Parse a Modus-A `insert.sql` file (as generated by this pipeline, three
`insert into practice_exercises/practice_context_blocks/practice_questions`
statements with dollar-quoted text fields) back into the JSON payload shape
expected by the `insert_full_exercise` Supabase RPC.

Exists so a failed/blocked STAP 7 (e.g. the insert_full_exercise RPC
rejecting an empty context_block_ids array) can be retried later purely from
the already-committed insert.sql, without re-doing any crop/OCR/upload work.

Usage:
    from sql_to_payload import parse_insert_sql
    payload = parse_insert_sql("output/havo-scheikunde-2023-ii/insert.sql")
    # payload == {"exercises": [...], "context_blocks": [...], "questions": [...]}

Deliberately hand-rolled rather than using a real SQL parser lib (none are
guaranteed available): the format is narrow and fixed (three known tables,
dollar-quoted text, 'uuid' strings, ::jsonb casts, array[...]::uuid[]), so a
small character-level scanner that respects $$...$$ and '...' quoting when
looking for top-level commas/semicolons/parens is enough and has no
dependencies.
"""

import json
import re


def _skip_dollar_quote(s, i):
    """If s[i:] starts a $$...$$ span, return the index just past its closing
    $$; otherwise return None."""
    if s.startswith("$$", i):
        end = s.find("$$", i + 2)
        if end == -1:
            raise ValueError("unterminated $$ quote")
        return end + 2
    return None


def _skip_single_quote(s, i):
    """If s[i] == \"'\", return the index just past the matching closing
    quote (handling '' as an escaped literal quote); otherwise return None."""
    if s[i] != "'":
        return None
    j = i + 1
    n = len(s)
    while j < n:
        if s[j] == "'" and j + 1 < n and s[j + 1] == "'":
            j += 2
            continue
        if s[j] == "'":
            return j + 1
        j += 1
    raise ValueError("unterminated ' quote")


def split_statements(text):
    """Split a SQL file into individual statements on top-level (paren-depth
    0, outside any quoting) semicolons. Exam text can itself contain ';', so
    a naive regex split on literal ';' is not safe -- this walks the string
    respecting $$...$$ and '...' spans."""
    statements = []
    i, n, start, depth = 0, len(text), 0, 0
    while i < n:
        skip = _skip_dollar_quote(text, i)
        if skip is not None:
            i = skip
            continue
        skip = _skip_single_quote(text, i)
        if skip is not None:
            i = skip
            continue
        c = text[i]
        if c == "(":
            depth += 1
        elif c == ")":
            depth -= 1
        elif c == ";" and depth == 0:
            statements.append(text[start:i])
            start = i + 1
        i += 1
    tail = text[start:].strip()
    if tail:
        statements.append(tail)
    return [s.strip() for s in statements if s.strip()]


def split_top_level(s):
    """Split s on commas at depth 0 (outside $$...$$, '...', and nested
    (...)/[...]) -- used both for a row's column values and for the contents
    of an array[...] literal."""
    items = []
    i, n, start, depth = 0, len(s), 0, 0
    while i < n:
        skip = _skip_dollar_quote(s, i)
        if skip is not None:
            i = skip
            continue
        skip = _skip_single_quote(s, i)
        if skip is not None:
            i = skip
            continue
        c = s[i]
        if c in "([":
            depth += 1
        elif c in ")]":
            depth -= 1
        elif c == "," and depth == 0:
            items.append(s[start:i])
            start = i + 1
        i += 1
    items.append(s[start:])
    return [it.strip() for it in items]


def _find_matching_paren(s, open_idx):
    """s[open_idx] must be '('. Return the index of its matching ')',
    respecting $$...$$/'...' quoting and nested parens."""
    i, n, depth = open_idx, len(s), 0
    while i < n:
        skip = _skip_dollar_quote(s, i)
        if skip is not None:
            i = skip
            continue
        skip = _skip_single_quote(s, i)
        if skip is not None:
            i = skip
            continue
        c = s[i]
        if c == "(":
            depth += 1
        elif c == ")":
            depth -= 1
            if depth == 0:
                return i
        i += 1
    raise ValueError("no matching )")


def extract_rows(values_text):
    """Given the text after `values` in an insert statement (with the
    trailing ';' already stripped by split_statements), return a list of
    rows, each a list of raw (unparsed) column-value strings."""
    rows = []
    i, n = 0, len(values_text)
    while i < n:
        while i < n and values_text[i] in " \n\t,":
            i += 1
        if i >= n:
            break
        if values_text[i] != "(":
            raise ValueError(f"expected '(' at offset {i}: ...{values_text[i:i + 40]!r}")
        end = _find_matching_paren(values_text, i)
        inner = values_text[i + 1:end]
        rows.append(split_top_level(inner))
        i = end + 1
    return rows


_STRING_CAST_RE = re.compile(r"^'(.*)'(::\w+)?$", re.S)


def parse_value(v):
    """Parse a single raw column-value string into a Python value (str,
    int, None, dict/list for ::jsonb, or list[str] for array[...]::uuid[])."""
    v = v.strip()
    if v == "NULL":
        return None
    if v.startswith("$$") and v.endswith("$$") and len(v) >= 4:
        return v[2:-2]
    if v.startswith("array["):
        start = v.index("[")
        end = v.index("]", start)
        inner = v[start + 1:end]
        if not inner.strip():
            return []
        return [parse_value(p) for p in split_top_level(inner)]
    if v.startswith("'"):
        m = _STRING_CAST_RE.match(v)
        if not m:
            raise ValueError(f"malformed quoted value: {v!r}")
        content = m.group(1).replace("''", "'")
        cast = m.group(2)
        if cast == "::jsonb":
            return json.loads(content)
        return content
    try:
        return int(v)
    except ValueError:
        return v


_HEADER_RE = re.compile(r"^insert\s+into\s+(practice_\w+)\s*\(([^)]*)\)\s*values\s*(.*)$", re.S | re.I)

_TABLE_TO_PAYLOAD_KEY = {
    "practice_exercises": "exercises",
    "practice_context_blocks": "context_blocks",
    "practice_questions": "questions",
}


def parse_insert_sql(path):
    """Parse a Modus-A insert.sql file into the {"exercises": [...],
    "context_blocks": [...], "questions": [...]} payload shape expected by
    the insert_full_exercise RPC."""
    with open(path, encoding="utf-8") as f:
        text = f.read()

    payload = {"exercises": [], "context_blocks": [], "questions": []}
    for statement in split_statements(text):
        m = _HEADER_RE.match(statement)
        if not m:
            raise ValueError(f"unrecognized statement head: {statement[:80]!r}")
        table, cols_raw, values_text = m.groups()
        key = _TABLE_TO_PAYLOAD_KEY.get(table)
        if key is None:
            raise ValueError(f"unexpected table in insert.sql: {table}")
        cols = [c.strip() for c in cols_raw.split(",")]
        for row in extract_rows(values_text):
            if len(row) != len(cols):
                raise ValueError(f"column/value count mismatch in {table}: {len(cols)} cols vs {len(row)} values")
            payload[key].append({col: parse_value(val) for col, val in zip(cols, row)})
    return payload
